# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-USAA
version:      1.5
version_from: USAA.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    DateTime::Format::Strptime:    0
    HTML::TableExtract:            0
    HTML::TokeParser::Simple:      0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
